### ISSUE TITLE
storage-server setup guide

### ISSUE THREAD

**Issue by danielstan422** [aqnouch/Signal-Setup-Guide#26]
Hi @aqnouch, 

First, I would like to thank you for the very helpful guides! Congrats!
Would you consider configuring 'storage-server' for a future guide?

**Comment by aqnouch** [comment]
Hello thanks for your kind encouragement,

Yes I'm trying to find time to work on the storage-server in as near future.

**Comment by mhkhung** [comment]
I am also now stuck at the storage server. It appears that groups V2 needs it. How are you guys interfacing with the service? I am using a forked version of signal-cli.

**Comment by mhkhung** [comment]
I got storage-server kinda working:

```
server:
  applicationConnectors:
  - type: http 
    port: 9090    # I run it in the same server as TextSecure
  adminConnectors:
  - type: http
    port: 9091    # I run it in the same server as TextSecure

# Use the same AWS keys from the TextSecure setup?
cdn: # aws cdn configuration 
  accessKey:    
  accessSecret: 
  region: ca-central-1
  bucket: 

bigtable:
  projectId: <you must have one created when creating gcm settings
  instanceId: 0
  clusterId: 0
  contactManifestsTableId: contactManifests
  contactsTableId: contacts
  groupsTableId: groups
  groupLogsTableId: groupLogs

authentication:
  key: <somerandomkey> # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`

# Copy from TextSecure config
zkConfig:
  serverSecret: 
  serverPublic: 

group:
  maxGroupSize: 1000
  maxGroupTitleLengthBytes: 200
  externalServiceSecret: <somerandomkey> # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`

```
The storage server builds/starts the same way as the signal server..

Now, google charges $500 a month min for BigTable.. so you will need to use the BigTable emulator instead..
- Install it to your machine - I used debian version.. https://cloud.google.com/sdk/docs/install
Make sure google-cloud-sdk-bigtable-emulator and google-cloud-sdk-cbt are also installed
- Start the emulator `gcloud beta emulators bigtable start`

Create the tables/column-families:
```
cbt -project myproject -instance 0 createtable contactManifests
cbt -project myproject -instance 0 createtable contacts
cbt -project myproject -instance 0 createtable groups
cbt -project myproject -instance 0 createtable groupLogs
cbt -instance 0 createfamily groups g
cbt -instance 0 createfamily groupLogs l
cbt -instance 0 createfamily contacts c
cbt -instance 0 createfamily contactManifests m
```
